### ISSUE TITLE
Errors when importing in Unity

### ISSUE THREAD

**Issue by CulturImage** [framefield/vr-annotate#2]
Dear author
I have jt loaded vr-annotate in Unity and I have encountered numerous errors. See attachment
Can you help on this?
I have all the dependencies in my project
Many thanks
Nic
![capture](https://user-images.githubusercontent.com/1540485/31746184-01e6a22e-b45e-11e7-97c7-c0c3e720262b.JPG)

**Comment by mutaphysis** [comment]
Hi @paganick,

it seems you have SteamVR imported twice. We have a version of SteamVR in `Assets/SteamVR` (see https://github.com/framefield/vr-annotate/tree/master/Assets/SteamVR) and I assume you already had SteamVR inside your own project.

I would recommend to remove the duplicate SteamVR version.
Do you have your sources available somewhere so that I can check more?

**Comment by CulturImage** [comment]
Hi and thanks a lot for your help.
I have just started a new project and I have copied the vr-annotate-master folder  into my asset folder (this is the only one I have at the moment) I still have all the errors. Attached you have the log. If you require the project I can send it but there is nothing in it only vr-annotate

Many thanks
Nic

ps. I am using Unity 2017.2.0f3 Pro
[vr-annoted_erros.txt](https://github.com/framefield/vr-annotate/files/1398026/vr-annoted_erros.txt)

**Comment by mutaphysis** [comment]
Hi @paganick,

the vr-annotate is a complete unity project, there is no need to put it inside an existing project. 

So instead of having something like `Assets/vr-annotate-master/vr-annotate-master/Assets/` the files should be directly in `Assets`. 

But the main problem is that some resources seem to be invalid or missing - my assumption is that you tried to clone the project without having git-lfs installed on your system.

Can you try to clone again after following https://help.github.com/articles/installing-git-large-file-storage/ ?

You probably downloaded the repository via the `DOWNLOAD zip` link - (e.g. https://github.com/framefield/vr-annotate/archive/master.zip ). This will not include most of the resources, as these are stored elsewhere via git-lfs.


Hope this helps,
Henrik

**Comment by CulturImage** [comment]
Ok almost there...
I have cloned the project into my desktop GitHub and open vr-annotate as a project.
I get 3 errors and 35 warning
Here are the screenshots
![capture1](https://user-images.githubusercontent.com/1540485/31768638-21c031a4-b4c8-11e7-8a08-815dd91f7da9.JPG)
![capture2](https://user-images.githubusercontent.com/1540485/31768639-21da8b9e-b4c8-11e7-84cf-55f748bbe834.JPG)

**Comment by mutaphysis** [comment]
Cool, looks mostly good - I think you can ignore the two missing folders, they will be generated at runtime and these files where added by accident.

I think the XR OpenVR error is a bit more serious - could it be that Unity has some problems finding the SteamVR installation on your system? See also https://support.steampowered.com/kb_article.php?ref=2001-UXCM-4439#install-steam 

If this does not help, @gdominikff or @pixtur might have some ideas, as I did not work on this project :)


bye,
Henrik

**Comment by CulturImage** [comment]
Ok yes he had some problems because SteamVR was not installed, installed now.
Only 2 errors now (the warnings go away when playing the scene)

XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_HmdNotFoundPresenceFailed: "Hmd Not Found Presence Failed (126)"!

Failed to load IVRRenderModels interface version IVRRenderModels_005
UnityEngine.Debug:LogError(Object)
RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:281)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

I don't have an HMD, is it possible to use vr-annotate without steamvr? I only need to export for desktops for the moments.
Many thanks!

**Comment by mutaphysis** [comment]
Sorry, Steam VR is a requirement at the moment. 

We are open for pull requests for non VR camera support, but changing the interaction to a regular desktop will be quite an undertaking, and nothing is planned for this so far.

bye,
Henrik
